import { Config } from "effect"

export function truthy(key: string) {
  const value = process.env[key]?.toLowerCase()
  return value === "true" || value === "1"
}

const copy = process.env["OPENRESEARCH_EXPERIMENTAL_DISABLE_COPY_ON_SELECT"]
const fff = process.env["OPENRESEARCH_DISABLE_FFF"]

function enabledByExperimental(key: string) {
  return process.env[key] === undefined ? truthy("OPENRESEARCH_EXPERIMENTAL") : truthy(key)
}

export const Flag = {
  OTEL_EXPORTER_OTLP_ENDPOINT: process.env["OTEL_EXPORTER_OTLP_ENDPOINT"],
  OTEL_EXPORTER_OTLP_HEADERS: process.env["OTEL_EXPORTER_OTLP_HEADERS"],

  OPENRESEARCH_AUTO_HEAP_SNAPSHOT: truthy("OPENRESEARCH_AUTO_HEAP_SNAPSHOT"),
  OPENRESEARCH_GIT_BASH_PATH: process.env["OPENRESEARCH_GIT_BASH_PATH"],
  OPENRESEARCH_CONFIG: process.env["OPENRESEARCH_CONFIG"],
  OPENRESEARCH_CONFIG_CONTENT: process.env["OPENRESEARCH_CONFIG_CONTENT"],
  OPENRESEARCH_DISABLE_AUTOUPDATE: truthy("OPENRESEARCH_DISABLE_AUTOUPDATE"),
  OPENRESEARCH_ALWAYS_NOTIFY_UPDATE: truthy("OPENRESEARCH_ALWAYS_NOTIFY_UPDATE"),
  OPENRESEARCH_DISABLE_PRUNE: truthy("OPENRESEARCH_DISABLE_PRUNE"),
  OPENRESEARCH_DISABLE_TERMINAL_TITLE: truthy("OPENRESEARCH_DISABLE_TERMINAL_TITLE"),
  OPENRESEARCH_SHOW_TTFD: truthy("OPENRESEARCH_SHOW_TTFD"),
  OPENRESEARCH_DISABLE_AUTOCOMPACT: truthy("OPENRESEARCH_DISABLE_AUTOCOMPACT"),
  OPENRESEARCH_DISABLE_MODELS_FETCH: truthy("OPENRESEARCH_DISABLE_MODELS_FETCH"),
  OPENRESEARCH_DISABLE_MOUSE: truthy("OPENRESEARCH_DISABLE_MOUSE"),
  OPENRESEARCH_FAKE_VCS: process.env["OPENRESEARCH_FAKE_VCS"],
  OPENRESEARCH_SERVER_PASSWORD: process.env["OPENRESEARCH_SERVER_PASSWORD"],
  OPENRESEARCH_SERVER_USERNAME: process.env["OPENRESEARCH_SERVER_USERNAME"],
  OPENRESEARCH_DISABLE_FFF: fff === undefined ? process.platform === "win32" : truthy("OPENRESEARCH_DISABLE_FFF"),

  // Experimental
  OPENRESEARCH_EXPERIMENTAL_FILEWATCHER: Config.boolean("OPENRESEARCH_EXPERIMENTAL_FILEWATCHER").pipe(
    Config.withDefault(false),
  ),
  OPENRESEARCH_EXPERIMENTAL_DISABLE_FILEWATCHER: Config.boolean("OPENRESEARCH_EXPERIMENTAL_DISABLE_FILEWATCHER").pipe(
    Config.withDefault(false),
  ),
  OPENRESEARCH_EXPERIMENTAL_DISABLE_COPY_ON_SELECT:
    copy === undefined ? process.platform === "win32" : truthy("OPENRESEARCH_EXPERIMENTAL_DISABLE_COPY_ON_SELECT"),
  OPENRESEARCH_MODELS_URL: process.env["OPENRESEARCH_MODELS_URL"],
  OPENRESEARCH_MODELS_PATH: process.env["OPENRESEARCH_MODELS_PATH"],
  OPENRESEARCH_DB: process.env["OPENRESEARCH_DB"],

  OPENRESEARCH_WORKSPACE_ID: process.env["OPENRESEARCH_WORKSPACE_ID"],
  OPENRESEARCH_EXPERIMENTAL_WORKSPACES: enabledByExperimental("OPENRESEARCH_EXPERIMENTAL_WORKSPACES"),

  // Evaluated at access time (not module load) because tests, the CLI, and
  // external tooling set these env vars at runtime.
  get OPENRESEARCH_DISABLE_PROJECT_CONFIG() {
    return truthy("OPENRESEARCH_DISABLE_PROJECT_CONFIG")
  },
  get OPENRESEARCH_DISABLE_PLUGIN_DEPENDENCY_INSTALL() {
    return truthy("OPENRESEARCH_DISABLE_PLUGIN_DEPENDENCY_INSTALL")
  },
  get OPENRESEARCH_EXPERIMENTAL_REFERENCES() {
    return enabledByExperimental("OPENRESEARCH_EXPERIMENTAL_REFERENCES")
  },
  get OPENRESEARCH_TUI_CONFIG() {
    return process.env["OPENRESEARCH_TUI_CONFIG"]
  },
  get OPENRESEARCH_CONFIG_DIR() {
    return process.env["OPENRESEARCH_CONFIG_DIR"]
  },
  get OPENRESEARCH_PURE() {
    return truthy("OPENRESEARCH_PURE")
  },
  get OPENRESEARCH_PERMISSION() {
    return process.env["OPENRESEARCH_PERMISSION"]
  },
  get OPENRESEARCH_PLUGIN_META_FILE() {
    return process.env["OPENRESEARCH_PLUGIN_META_FILE"]
  },
  get OPENRESEARCH_CLIENT() {
    return process.env["OPENRESEARCH_CLIENT"] ?? "cli"
  },
}
